name: Build APK Final Teruji
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Pasang Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Pasang Alat Tukang
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Pasang Buildozer
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.33 buildozer

      - name: Proses Rakit APK
        run: |
          export APP_ALLOW_ROOT=1
          yes | buildozer -v android debug

      - name: Simpan Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-Update-Vivo-Berhasil
          path: bin/*.apk
