name: Build-APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          sudo fallocate -l 4G /s && sudo mkswap /s && sudo swapon /s
          pip install Cython==0.29.33 buildozer
      - name: Rakit
        run: |
          export APP_ALLOW_ROOT=1
          buildozer -v android debug
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-APK
          path: bin/*.apk
