name: Build APK Vivo Final
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake
      - name: Build with Buildozer
        uses: ArtemGrinev/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: master
        env:
          APP_ALLOW_ROOT: 1
      - name: Upload Result
        uses: actions/upload-artifact@v2
        with:
          name: APK-Update-Vivo
          path: bin/*.apk
