name: Build APK Vivo Final
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake

      - name: Build with Buildozer
        uses: ArtemGrinev/buildozer-action@v1.6.1
        with:
          command: buildozer android debug
        env:
          APP_ALLOW_ROOT: 1

      - name: Upload APK Hasil
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-Vivo-Jadi
          path: bin/*.apk
