name: Build-APK-Vivo
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Tambah Memori Extra
        run: |
          sudo fallocate -l 6G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install Cython==0.29.33 buildozer

      - name: Rakit APK (Auto License)
        run: |
          export APP_ALLOW_ROOT=1
          # Perintah 'yes' ini penting banget buat lewatin lisensi SDK
          yes | buildozer -v android debug
